spring.application.name=CompraCerta-core

spring.datasource.url=jdbc:h2:mem:ccdb
# spring.datasource.url=jdbc:h2:tcp://localhost:9092//opt/h2-data/veiculosdb --QUANDO CONFUGURAR E EXECUTAR VIA DOCKER COMPOSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


management.health.probes.enabled=true
server.shutdown=graceful