apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:h2:tcp://h2-service:9092/mem:veiculosdb"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-app-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c2E=
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=