apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:veiculosdb"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
